name: Build Project

on: [push, pull_request, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Information
        run: ./gradlew tasks project dependencies
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30

    name: Gradle Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Build
        run: ./gradlew build -x test
  
  test:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      checks: write
      pull-requests: write

    name: Gradle Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Setup Servers
        run: bash .github/test.sh
      - name: Gradle Test
        run: ./gradlew test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop Servers
        if: success() || failure()
        run: |
          rm -rf /tmp/admin.password

          docker stop jenkins-rest nexus-rest mariadb
          docker rm jenkins-rest nexus-rest mariadb 
          docker network rm codemc
      - name: Archive Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/
      - name: Collect JaCoCo Report
        if: ${{ github.event_name != 'pull_request' }}
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: build/jacoco.xml
          coverage_report_name: Code Coverage
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      - name: Print JaCoCo Report
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage % | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

      - name: Upload Code Coverage Artifacts (Push)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: "*/coverage-results.md"

      - name: Upload Code Coverage Artifacts (Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: build/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          pass-emoji: ✅
          min-coverage-overall: 80
          min-coverage-changed-files: 85
